'use client'
import './globals.css'
import type { Metadata } from 'next'
import { Roboto, Stylish } from 'next/font/google'
import Header from './components/Header'
import Footer from './components/Footer'
import Providers from './providers/providers'

import { usePathname } from 'next/navigation'
import { checkIsPublicRoute } from './utiuls/check-is-public-route'

import PrivateRoute from './privateRoute'

export const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin']
})

export const stylish = Stylish({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--stylish'
})

export const metadata: Metadata = {
  title: 'Você é o Chef',
  description: 'Generated by create next app',
}

export default function RootLayout ({
  children,
}: {
  children: React.ReactNode
}) {

  const path = usePathname()
  const isPublic = checkIsPublicRoute(path)

  return (
    <html lang="pt-br">
      <body className={`${roboto.className} ${stylish.variable} flex flex-col`}>
        <Providers>
          {isPublic && children}

          {!isPublic && <PrivateRoute>
            <Header />
            {children}
            <Footer />
          </PrivateRoute>
          }
        </Providers>
      </body>
    </html>
  )
}