'use client'
import './globals.css'
import type { Metadata } from 'next'
import { Roboto, Stylish } from 'next/font/google'
import Header from './components/Header'
import Footer from './components/Footer'
import Providers from './providers/providers'
import Login from './pages/login/page'
import { usePathname } from 'next/navigation'


const user = true

export const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin']
})

export const stylish = Stylish({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--stylish'
})

export const metadata: Metadata = {
  title: 'Você é o Chef',
  description: 'Generated by create next app',
}

export default function RootLayout ({
  children,
}: {
  children: React.ReactNode
}) {

  const path = usePathname()
  console.log('ROTA:', path)

  return (
    <html lang="pt-br">
      <body className={`${roboto.className} ${stylish.variable} flex flex-col`}>
        <Providers>
          {user ? <Login /> :
            <>
              <Header />
              {children}
              <Footer />
            </>
          }
        </Providers>
      </body>
    </html>
  )
}
