import './globals.css'
import type { Metadata } from 'next'
import { Roboto, Stylish } from 'next/font/google'
import Header from './components/Header'

export const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin']
})

export const stylish = Stylish({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--stylish'
})

export const metadata: Metadata = {
  title: 'Você é o Chef',
  description: 'Generated by create next app',
}

export default function RootLayout ({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={`${roboto.className} ${stylish.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  )
}
